{{- if (and .Values.flower.enabled (not .Values.flower.existing_secret)) }}
---
{{- $credentials := printf "flower:%s" .Values.flower.default_password }}
apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: {{ .Values.flower.secret_name }}
  labels:
    app: {{ .Values.flower.secret_name }}
  annotations:
    helm.sh/resource-policy: keep
data:
  FLOWER_BASIC_AUTH_CREDENTIALS: {{ $credentials | b64enc}}
{{- end -}}
