{{- if .Values.haproxy.enabled -}}
---
{{- if .Capabilities.APIVersions.Has "apps.openshift.io/v1/DeploymentConfig" }}
apiVersion: apps.openshift.io/v1
kind: DeploymentConfig
{{- else }}
apiVersion: apps/v1
kind: Deployment
{{- end }}
metadata:
  name: haproxy
spec:
  replicas: 1
  {{- if not (.Capabilities.APIVersions.Has "apps.openshift.io/v1/DeploymentConfig") }}
  selector:
    matchLabels:
      app: haproxy
  {{- end }}
  template:
    metadata:
      labels:
        app: haproxy
    spec:
      containers:
        - name: haproxy
          image: {{ .Values.haproxy.image }}
          ports:
            - containerPort: 8080
              protocol: TCP
          volumeMounts:
            - name: haproxy-config
              mountPath: /usr/local/etc/haproxy
          {{- if .Values.haproxy.resources }}
          resources: {{- toYaml .Values.haproxy.resources | nindent 12 }}
          {{- end }}
      volumes:
        - name: haproxy-config
          configMap:
            name: haproxy-config
  {{- end -}}
