{{- if .Values.haproxy.inside_cluster -}}
---
{{- if .Capabilities.APIVersions.Has "apps.openshift.io/v1/DeploymentConfig" }}
apiVersion: apps.openshift.io/v1
kind: DeploymentConfig
{{- else }}
apiVersion: apps/v1
kind: Deployment
{{- end }}
metadata:
  name: haproxy
spec:
  replicas: 1
  {{- if not .Capabilities.APIVersions.Has "apps.openshift.io/v1/DeploymentConfig" }}
  selector:
    matchLabels:
      app: haproxy
  {{- end }}
  template:
    metadata:
      labels:
        app: haproxy
    spec:
      containers:
        - name: haproxy
          image: haproxy:2.1.3
          ports:
            - containerPort: 8080
              protocol: TCP
          volumeMounts:
            - name: haproxy-config
              mountPath: /usr/local/etc/haproxy
      volumes:
        - name: haproxy-config
          configMap:
            name: haproxy-config
  {{- end -}}
