# WARNING: do not use in production!
# See <https://opensearch.org/docs/latest/opensearch/install/helm/> instead.
{{- if .Values.search.enabled -}}
---
{{- if .Capabilities.APIVersions.Has "apps.openshift.io/v1/DeploymentConfig" }}
apiVersion: apps.openshift.io/v1
kind: DeploymentConfig
{{- else }}
apiVersion: apps/v1
kind: Deployment
{{- end }}
metadata:
  name: search
spec:
  replicas: 1
  {{- if not (.Capabilities.APIVersions.Has "apps.openshift.io/v1/DeploymentConfig") }}
  selector:
    matchLabels:
      app: search
  {{- end }}
  template:
    metadata:
      labels:
        app: search
    spec:
      containers:
        - name: search
          image: opensearchproject/opensearch:2.3.0
          ports:
            - containerPort: 9200
            - containerPort: 9600
          resources:
            requests:
              cpu: "1"
              memory: 512Mi
            limits:
              cpu: "2"
              memory: 1Gi
          env:
            - name: TZ
              value: "Europe/Zurich"
            - name: network.host
              value: "0.0.0.0"
            - name: "discovery.type"
              value: "single-node"
            - name: "bootstrap.memory_lock"
              value: "true"
            - name: OPENSEARCH_JAVA_OPTS
              value: "-Xms512m -Xmx512m"
            - name: "DISABLE_SECURITY_PLUGIN"
              value: "true"
          volumeMounts:
            - name: data
              mountPath: /usr/share/opensearch/data
          readinessProbe:
            httpGet:
              path: /
              port: 9200
              scheme: HTTP
            initialDelaySeconds: 60
            timeoutSeconds: 5
            successThreshold: 3
          livenessProbe:
            httpGet:
              path: /_cluster/health
              port: 9200
              scheme: HTTP
            initialDelaySeconds: 360
            timeoutSeconds: 5
      volumes:
        - name: data
          emptyDir: {}
{{- end -}}
