{{- if .Values.postgresql.inside_cluster -}}
---
{{- if .Capabilities.APIVersions.Has "apps.openshift.io/v1/DeploymentConfig" }}
apiVersion: apps.openshift.io/v1
kind: DeploymentConfig
{{- else }}
apiVersion: apps/v1
kind: Deployment
{{- end }}
metadata:
  name: db
spec:
  replicas: 1
  {{- if not .Capabilities.APIVersions.Has "apps.openshift.io/v1/DeploymentConfig" }}
  selector:
    matchLabels:
      app: db
  {{- end }}
  template:
    metadata:
      labels:
        app: db
    spec:
      containers:
        - name: db
          image: centos/postgresql-95-centos7
          ports:
            - containerPort: 5432
          env:
            - name: TZ
              value: "Europe/Zurich"
            - name: POSTGRESQL_USER
              valueFrom:
                secretKeyRef:
                  name: {{ include "postgresql.secret_name" . }}
                  key: POSTGRESQL_USER
            - name: POSTGRESQL_DATABASE
              valueFrom:
                secretKeyRef:
                  name: {{ include "postgresql.secret_name" . }}
                  key: POSTGRESQL_DATABASE
            - name: POSTGRESQL_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{  include "postgresql.secret_name" . }}
                  key: POSTGRESQL_PASSWORD
          volumeMounts:
            - name: data
              mountPath: /var/lib/pgsql/data
          readinessProbe:
            exec:
              command:
                - sh
                - -i
                - -c
                - "pg_isready"
            initialDelaySeconds: 15
            timeoutSeconds: 5
      volumes:
        - name: data
          emptyDir: {}
{{- end -}}
