---
{{- if .Capabilities.APIVersions.Has "route.openshift.io/v1/Route" }}
apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: invenio
spec:
  host: {{ .Values.host }}
  to:
    kind: Service
    name: {{ if .Values.haproxy.enabled }}haproxy{{ else }}web{{ end }}
  port:
    targetPort: http
  tls:
    insecureEdgeTerminationPolicy: Redirect
    termination: edge
{{- else }}
{{- if .Values.ingress.enabled }}
{{- if .Capabilities.APIVersions.Has "networking.k8s.io/v1/Ingress" }}
apiVersion: networking.k8s.io/v1
{{- else }}
apiVersion: networking.k8s.io/v1beta1
{{- end }}
kind: Ingress
metadata:
  name: invenio-ingress
  annotations:
    {{- if .Values.ingress.class }}
    kubernetes.io/ingress.class: {{ .Values.ingress.class }}
    {{- end }}
    nginx.ingress.kubernetes.io/force-ssl-redirect: "true"
    nginx.ingress.kubernetes.io/proxy-request-buffering: "off"
    nginx.ingress.kubernetes.io/proxy-body-size: "0"
    nginx.ingress.kubernetes.io/client-body-buffer-size: "8m"
    nginx.ingress.kubernetes.io/proxy-buffer-size: "8m"
    nginx.ingress.kubernetes.io/proxy-read-timeout: "240"
    nginx.ingress.kubernetes.io/proxy-send-timeout: "240"
    nginx.ingress.kubernetes.io/configuration-snippet: |
      send_timeout 240s;
      client_body_timeout 240s;
spec:
  tls:
    - hosts:
        - "{{ .Values.host }}"
      secretName: {{ .Values.ingress.sslSecretName }}
  rules:
    - host: "{{ .Values.host }}"
      http:
        paths:
          - path: ""
            backend:
              serviceName: {{ if .Values.haproxy.enabled }}haproxy{{ else }}web{{ end }}
              servicePort: http
{{- end }}
{{- end }}