{{- if not (.Values.search.existing_secret) }}
---
apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: {{ .Values.search.secret_name }}
  labels:
    app: {{ .Values.search.secret_name }}
  annotations:
    helm.sh/resource-policy: keep
data:
  SEARCH_USER: {{ .Values.search.user | b64enc }}
  SEARCH_PASSWORD: {{ .Values.search.password | b64enc }}
  INVENIO_SEARCH_HOSTS: {{ .Values.search.invenio_hosts | b64enc }}
{{- end -}}
