{{- if not (.Values.postgresql.existing_secret) }}
---
apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: {{ .Values.postgresql.secret_name }}
  labels:
    app: {{ .Values.postgresql.secret_name }}
  annotations:
    helm.sh/resource-policy: keep
data:
  POSTGRESQL_USER: {{ .Values.postgresql.user | b64enc }}
  POSTGRESQL_PASSWORD: {{ .Values.postgresql.password | b64enc }}
  POSTGRESQL_HOST: {{ .Values.postgresql.host | b64enc }}
  POSTGRESQL_PORT: {{ .Values.postgresql.port | b64enc }}
  POSTGRESQL_DATABASE: {{ .Values.postgresql.database | b64enc }}
  SQLALCHEMY_DB_URI: {{ .Values.postgresql.sqlalchemy_db_uri | b64enc }}
{{- end -}}
