---
kind: "Template"
apiVersion: "v1"
metadata:
  name: "parametrized-cron-job"
  creationTimestamp: null
  annotations:
    description: "Invenio job OpenShift template."
    tags: "invenio-cron-job"
labels:
  template: "invenio-cron-job"
objects:
  - apiVersion: batch/v1beta1
    kind: CronJob
    metadata:
      name: "${JOB_NAME}"
    spec:
      schedule: "*/5 * * * *"
      jobTemplate:
        spec:
          template:
            spec:
              restartPolicy: Never
              containers:
              - name: invenio-job
                image: {{ .Values.web.image }}
                command:
                  - /bin/bash
                  - -c
                  - "${JOB_COMMAND}"
                resources:
                  requests:
                    cpu: 200
                    memory: 1Gi
                  limits:
                    cpu: 1
                    memory: 2Gi
                envFrom:
                - configMapRef:
                    name: invenio-config
                env:
                - name: TZ
                  value: "Europe/Zurich"
                - name: INVENIO_BROKER_URL
                  valueFrom:
                    secretKeyRef:
                      name: {{ .Values.rabbitmq.secret_name }}
                      key: CELERY_BROKER_URL
                - name: INVENIO_CELERY_BROKER_URL
                  valueFrom:
                    secretKeyRef:
                      name: {{ .Values.rabbitmq.secret_name }}
                      key: CELERY_BROKER_URL
                - name: INVENIO_SQLALCHEMY_DATABASE_URI
                  valueFrom:
                    secretKeyRef:
                      name: {{ .Values.postgresql.secret_name }}
                      key: SQLALCHEMY_DB_URI
                - name: SEARCH_PASSWORD
                  valueFrom:
                    secretKeyRef:
                      name: {{ .Values.search.secret_name }}
                      key: SEARCH_PASSWORD
parameters:
  - name: JOB_NAME
    required: true
  - name: JOB_COMMAND
    required: true
