---
apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: mq-secrets
  labels:
    app: mq-secrets
data:
  RABBITMQ_DEFAULT_PASS: {{ .Values.rabbitmq.default_password | b64enc }}
  CELERY_BROKER_URL: {{ .Values.rabbitmq.celery_broker_uri | b64enc }}

---
apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: db-secrets
  labels:
    app: db-secrets
data:
  POSTGRESQL_USER: {{ .Values.postgresql.user | b64enc }}
  POSTGRESQL_PASSWORD: {{ .Values.postgresql.password | b64enc }}
  POSTGRESQL_HOST: {{ .Values.postgresql.host | b64enc }}
  POSTGRESQL_PORT: {{ .Values.postgresql.port | b64enc }}
  POSTGRESQL_DATABASE: {{ .Values.postgresql.database | b64enc }}
  SQLALCHEMY_DB_URI: {{ .Values.postgresql.sqlalchemy_db_uri | b64enc }}

---
apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: elasticsearch-secrets
  labels:
    app: elasticsearch-secrets
data:
  ELASTICSEARCH_USER: {{ .Values.elasticsearch.user | b64enc }}
  ELASTICSEARCH_PASSWORD: {{ .Values.elasticsearch.password | b64enc }}
  INVENIO_SEARCH_ELASTIC_HOSTS: {{ .Values.elasticsearch.invenio_hosts | b64enc }}

---
apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: invenio-secrets
  labels:
    app: invenio-secrets
data:
  INVENIO_SECRET_KEY: {{ .Values.invenio.secret_key | b64enc }}
