{{- if .Values.redis.enabled -}}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: cache
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cache
  template:
    metadata:
      labels:
        app: cache
    spec:
      volumes:
        - name: redis-volume
          persistentVolumeClaim:
            claimName: redis-volume
      containers:
        - name: cache
          image: {{ .Values.redis.image }}
          env:
            - name: TZ
              value: "Europe/Zurich"
          ports:
            - containerPort: 6379
              name: tcp
          volumeMounts:
            - name: redis-volume
              mountPath: /data
          readinessProbe:
            exec:
              command:
                - sh
                - -c
                - "redis-cli -h $(hostname) ping"
            initialDelaySeconds: 15
            timeoutSeconds: 5
          {{- if .Values.redis.resources }}
          resources: {{- toYaml .Values.redis.resources | nindent 12 }}
          {{- end }}
{{- end -}}
