{{- if .Values.redis.enabled -}}
---
apiVersion: v1
kind: Service
metadata:
  name: cache
  labels:
    run: cache
spec:
  ports:
  - port: 6379
    protocol: TCP
  selector:
    app: cache
{{- end }}
