---
apiVersion: v1
kind: Service
metadata:
  name: web
  labels:
    run: web
  {{- if .Values.web.annotations }}
  annotations: {{- toYaml .Values.web.annotations | nindent 4 }}
  {{- end }}
spec:
  ports:
    - name: 'http'
      port: 80
      targetPort: 8080
  selector:
    app: web
