{{- if .Values.haproxy.enabled -}}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: haproxy
spec:
  replicas: {{ .Values.haproxy.replicas }}
  selector:
    matchLabels:
      app: haproxy
  template:
    metadata:
      labels:
        app: haproxy
    spec:
      containers:
        - name: haproxy
          image: {{ required "Missing .Values.haproxy.image" .Values.haproxy.image }}
          ports:
            - containerPort: 8080
              protocol: TCP
          volumeMounts:
            - name: haproxy-config
              mountPath: /usr/local/etc/haproxy/haproxy.cfg
              subPath: haproxy.cfg
            - name: haproxy-config
              mountPath: /usr/local/etc/haproxy/denylist-ips.acl
              subPath: denylist-ips.acl
            - name: haproxy-config
              mountPath: /usr/local/etc/haproxy/denylist-ua.acl
              subPath: denylist-ua.acl
            - name: haproxy-config
              mountPath: /usr/local/etc/haproxy/error429.http
              subPath: error429.http
            - name: haproxy-config
              mountPath: /usr/local/etc/haproxy/backup-website.http
              subPath: backup-website.http
          {{- if .Values.haproxy.resources }}
          resources: {{- toYaml .Values.haproxy.resources | nindent 12 }}
          {{- end }}
      volumes:
        - name: haproxy-config
          configMap:
            name: haproxy-config
  {{- end -}}
