{{- if and (.Values.invenio.datacite.enabled) (not (or .Values.invenio.datacite.existingSecret .Values.invenio.datacite.existing_secret))}}
---
apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: {{ include "invenio.dataciteSecretName" . }}
  labels:
    {{- include "invenio.labels" . | nindent 4 }}
  annotations:
    helm.sh/resource-policy: keep
data:
  DATACITE_PASSWORD: {{ .Values.invenio.datacite.password | b64enc }}
  DATACITE_USERNAME: {{ .Values.invenio.datacite.username | b64enc }}
{{- end -}}
