{{- if .Values.invenio.extra_secrets }}
{{- range $key, $value := .Values.invenio.extra_secrets }}
{{- if and ($value.enabled) (not $value.existing_secret) }}
---
apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: {{ $value.secret_name }}
  labels:
    app: {{ $value.secret_name }}
  annotations:
    helm.sh/resource-policy: keep
data:
    {{- range $secret_key, $secret_value := $value }}
    {{ $secret_key }}: {{ $secret_value | toYaml | indent 4 | trim }}
    {{- end }}
{{- end }}
{{- end }}
{{- end }}
