{{- if not (.Capabilities.APIVersions.Has "route.openshift.io/v1/Route") }}
{{- if .Values.ingress.enabled }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "invenio.fullname" . }}
  {{- if .Values.ingress.annotations }}
  annotations:
    {{- .Values.ingress.annotations | toYaml | nindent 4}}
  {{- end }}
  labels:
    {{- include "invenio.labels" . | nindent 4 }}
spec:
  {{- if .Values.ingress.class }}
  ingressClassName: {{ .Values.ingress.class }}
  {{- end }}
  tls:
    - hosts:
        - {{ include "invenio.hostname" $ }}
      secretName: {{ include "invenio.tlsSecretName" $ }}
  rules:
    - host: {{ include "invenio.hostname" $ }}
      http:
        paths:
          - path: /
            backend:
              service:
                {{- if .Values.haproxy.enabled }}
                name: haproxy
                {{- else }}
                name: {{ include "invenio.fullname" . }}-web
                {{- end }}
                port:
                  name: http
            pathType: Prefix
{{- end }}
{{- end }}
