---
apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-config
data:
  invenio.conf: |
    upstream web {
        server 127.0.0.1:5000 max_conns={{ .Values.nginx.max_conns }} fail_timeout=0;
    }

    # increase default max size of `map`
    map_hash_max_size 10000;
    map_hash_bucket_size 10000;

    # IPs deny list
    geo $http_x_forwarded_for $bad_ip {
      default            allow;
      # 192.168.1.1      deny;
      # 192.168.1.0/24   deny;
      # 192.168.0.0/16   deny;
      # 2001:db8::/48    deny;
{{ .Values.nginx.denied_ips | indent 6 }}
    }

    # User Agents deny list
    map $http_user_agent $bad_ua {
      default        allow;
      # Exact match
      # "Mozilla/5.0 (Linux; Android)"     deny;
      # Regex
      # "~PetalBot"                        deny;
{{ .Values.nginx.denied_uas | indent 6 }}
    }

    log_format trace '$remote_addr - $time_iso8601 "$request" '
        '$status $body_bytes_sent $request_length "$http_referer" '
        '"$http_user_agent" "$http_x_forwarded_for" rid=$request_id '
        'rt=$request_time uct="$upstream_connect_time" '
        'uht="$upstream_header_time" urt="$upstream_response_time" '
        'sid=$upstream_http_x_session_id uid=$upstream_http_x_user_id';
    access_log off;

    server {
        listen              8080;
        server_name         localhost;
        access_log /var/log/nginx/access.log trace;

        # General settings
        charset             utf-8;
        default_type        application/octet-stream;
        keepalive_timeout   65s;
        include             /etc/nginx/mime.types;
        sendfile            on;
        server_tokens       off;
        tcp_nodelay         on;
        tcp_nopush          on;
        types_hash_max_size 2048;

        # gzip
        gzip on;
        gzip_disable "msie6";
        gzip_http_version 1.1;
        gzip_comp_level 5;
        gzip_min_length 100;
        gzip_proxied any;
        gzip_types
            text/css
            text/html
            text/javascript
            text/plain
            text/xml
            application/json
            application/xml
            application/xml+rss
            application/x-javascript;
        gzip_vary on;

        # SSL configuration removed in the deployed env
        add_header Strict-Transport-Security "max-age=15768000"; # 6 months

        # Request ID tracing (allows end-to-end tracking of requests for better
        # troubleshooting)
        add_header X-Request-ID $request_id;

        # The request body is sent to the proxied server immediately as it is
        # received
        proxy_request_buffering off;

        # Sets the HTTP protocol v1.1 for proxying in order to not use the buffer
        # in case of chunked transfer encoding
        proxy_http_version 1.1;

        # include blocked IPs
        if ( $bad_ip = "deny" ) {
          return 403;
        }
        # include blocked User Agents
        if ( $bad_ua = "deny" ) {
          return 403;
        }

        location /ping {
          access_log off;
          return 200 "ok\n";
        }

        # Proxying to the application server
        ## UI server
        location / {
          uwsgi_pass web;
          include uwsgi_params;

          uwsgi_read_timeout 180s;
          uwsgi_send_timeout 180s;

          uwsgi_buffering off;
          uwsgi_request_buffering off;

          uwsgi_param Host $host;
          uwsgi_param X-Forwarded-For $proxy_add_x_forwarded_for;
          uwsgi_param X-Forwarded-Proto $scheme;
          # Pass request id to the ui server
          uwsgi_param X-Request-ID $request_id;
          # X-Session-ID / X-User-ID is read by nginx and included in the logs,
          # however we don't want to expose them to clients so we are hiding them.
          uwsgi_hide_header X-Session-ID;
          uwsgi_hide_header X-User-ID;
          # Max upload size (except for files) is set to 100mb as default.
          client_max_body_size {{ .Values.nginx.records.client_max_body_size }};
        }

        ## API except files
        location /api {
          uwsgi_pass web;
          include uwsgi_params;

          uwsgi_read_timeout 180s;
          uwsgi_send_timeout 180s;

          uwsgi_buffering off;
          uwsgi_request_buffering off;

          uwsgi_param Host $host;
          uwsgi_param X-Forwarded-For $proxy_add_x_forwarded_for;
          uwsgi_param X-Forwarded-Proto $scheme;
          # Pass request id to the api server
          uwsgi_param X-Request-ID $request_id;
          # X-Session-ID / X-User-ID is read by nginx and included in the logs,
          # however we don't want to expose them to clients so we are hiding them.
          uwsgi_hide_header X-Session-ID;
          uwsgi_hide_header X-User-ID;
          # Max upload size (except for files) is set to 100mb as default.
          client_max_body_size {{ .Values.nginx.records.client_max_body_size }};
        }

        ## API files
        # Another location is defined in order to allow large file uploads in the files
        # API without exposing the other parts of the application to receive huge
        # request bodies.
        location ~ /api/records/.+/draft/files/.+/content {
          gzip off;
          uwsgi_pass web;
          include uwsgi_params;

          uwsgi_buffering off;
          uwsgi_request_buffering off;

          uwsgi_param Host $host;
          uwsgi_param X-Forwarded-For $proxy_add_x_forwarded_for;
          uwsgi_param X-Forwarded-Proto $scheme;
          # Pass request id to api server
          uwsgi_param X-Request-ID $request_id;
          # X-Session-ID / X-User-ID is read by nginx and included in the logs,
          # however we don't want to expose them to clients so we are hiding them.
          uwsgi_hide_header X-Session-ID;
          uwsgi_hide_header X-User-ID;
          # Max upload size for files is set to 50GB (configure as needed).
          client_max_body_size {{ .Values.nginx.files.client_max_body_size }};
        }

        # Static content is served directly by nginx and not the application server.
        # /static/dist can be cached forever because the filename is hashed
        location /static/dist {
          alias "{{ .Values.nginx.assets.location }}/dist";
          etag off;
          expires 1y;
          add_header Cache-Control "public";
          autoindex off;
          # prevent mime based attacks
          add_header X-Content-Type-Options nosniff;
        }

        # any other static will have the etag automatically generated by nginx
        location /static {
          alias "{{ .Values.nginx.assets.location }}";
          add_header Cache-Control "max-age=0, must-revalidate";
          autoindex off;
          # prevent mime based attacks
          add_header X-Content-Type-Options nosniff;
        }

        # Robots.txt file is served by nginx.
        location /robots.txt {
          alias {{ .Values.nginx.assets.location }}/robots.txt;
          autoindex off;
        }

{{ .Values.nginx.extra_server_config | indent 8 }}

    }
