{{- if (and .Values.persistence.enabled (not .Values.persistence.useExistingClaim)) }}
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: {{ .Values.persistence.name }}
  labels:
    app: web
  annotations:
    helm.sh/resource-policy: keep
    {{- if .Values.persistence.annotations }}
    {{- .Values.persistence.annotations | toYaml | nindent 4 }}
    {{- end }}
spec:
  {{- if .Values.persistence.storage_class }}
  storageClassName: {{ .Values.persistence.storage_class }}
  {{- end }}
  accessModes:
  - {{ .Values.persistence.access_mode }}
  resources:
    requests:
      storage: {{ .Values.persistence.size | quote }}
{{- end }}
