{{- if and (.Values.invenio.remote_apps.enabled) (not .Values.invenio.remote_apps.existing_secret) }}
---
apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: {{ .Values.invenio.remote_apps.secret_name }}
  labels:
    app: {{ .Values.invenio.remote_apps.secret_name }}
  annotations:
    helm.sh/resource-policy: keep
data:
  {{- range .Values.invenio.remote_apps.credentials }}
  {{ default (printf "INVENIO_%s_APP_CREDENTIALS" .name) }}: {{ printf "{\"consumer_key\": \"%s\" , \"consumer_secret\": \"%s\"}" .consumer_key .consumer_secret | b64enc }}
  {{- end }}
{{- end -}}
