{{- if not (.Values.invenio.existing_secret) }}
---
apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: invenio-secrets
  labels:
    app: invenio-secrets
  annotations:
    helm.sh/resource-policy: keep
data:
  INVENIO_SECRET_KEY: {{ required "Missing .Values.invenio.secret_key" .Values.invenio.secret_key | b64enc }}
  INVENIO_SECURITY_LOGIN_SALT: {{ required ".Values.invenio.security_login_salt " .Values.invenio.security_login_salt | b64enc }}
  INVENIO_CSRF_SECRET_SALT: {{ required ".Values.invenio.csrf_secret_salt " .Values.invenio.csrf_secret_salt | b64enc }}
{{- end -}}
