---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "invenio.fullname" . }}-worker-beat
  labels:
    {{- include "invenio.labels" . | nindent 4 }}
    app.kubernetes.io/component: worker-beat
spec:
  replicas: 1 # For data safety, beat must never have more than 1 replica!
  selector:
    matchLabels:
      app.kubernetes.io/component: worker-beat
  template:
    metadata:
      labels:
        app.kubernetes.io/component: worker-beat
    spec:
      containers:
      - name: worker-beat
        image: {{ required "Missing .Values.worker.image" .Values.worker.image }}
        command: [
          "/bin/bash",
          "-c",
          "celery -A {{ .Values.worker.app }} beat -l {{ .Values.worker.log_level }} -s {{ .Values.worker.celery_schedule }} --pidfile {{ .Values.worker.celery_pidfile }}"
        ]
        securityContext:
          {{- with .Values.workerBeat.securityContext }}
          {{- toYaml . | nindent 10 }}
          {{- end }}
        volumeMounts:
        - name: var-run-celery
          mountPath: {{ .Values.worker.run_mount_path }}
        {{- if .Values.persistence.enabled }}
        - mountPath: /opt/invenio/var/instance/data
          name: shared-volume
        {{- end }}
        {{- range $key, $value := .Values.invenio.vocabularies }}
        - name: vocabularies
          mountPath: "/opt/invenio/var/instance/app_data/vocabularies/{{ $key }}"
          subPath: "{{ $key }}"
        {{- end }}
        envFrom:
        - configMapRef:
            name: {{ include "invenio.fullname" . }}-config
        - secretRef:
            name: {{ include "invenio.secretName" . }}
        env:
        - name: TZ
          value: {{ required "Missing .Values.global.timezone" .Values.global.timezone }}
        - name: INVENIO_BROKER_URL
          value: {{ include "invenio.rabbitmq.uri" . }}
        - name: INVENIO_CELERY_BROKER_URL
          value: {{ include "invenio.rabbitmq.uri" . }}
        - name: INVENIO_SQLALCHEMY_DATABASE_URI
          value: {{ include "invenio.sqlAlchemyDbUri" . }}
        {{- with .Values.workerBeat.extraEnvVars }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
        {{- include "invenio.config.sentry" . | nindent 8 }}
        {{- if .Values.invenio.datacite.enabled }}
        - name: INVENIO_DATACITE_USERNAME
          valueFrom:
            secretKeyRef:
              name: {{ .Values.invenio.datacite.secret_name }}
              key: DATACITE_USERNAME
        - name: INVENIO_DATACITE_PASSWORD
          valueFrom:
            secretKeyRef:
              name: {{ .Values.invenio.datacite.secret_name }}
              key: DATACITE_PASSWORD
        {{- end }}
        {{- range .Values.invenio.extra_env_from_secret }}
        - name: {{ .name }}
          valueFrom:
            secretKeyRef:
              name: {{ .valueFrom.secretKeyRef.name }}
              key: {{ .valueFrom.secretKeyRef.key }}
        {{- end }}
        livenessProbe:
          exec:
            command:
              - /bin/bash
              - -c
              - "celery -A {{ .Values.worker.app }} inspect ping"
          initialDelaySeconds: 20
          timeoutSeconds: 30
        {{- if .Values.worker.resources }}
        resources: {{- toYaml .Values.workerBeat.resources | nindent 10 }}
        {{- else }}
        resources:
          requests:
            cpu: 500m
            memory: 200Mi
          limits:
            cpu: '2'
            memory: 500Mi
        {{- end }}
      securityContext:
        {{- with .Values.workerBeat.podSecurityContext }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
      volumes:
      - name: var-run-celery
        emptyDir:
          medium: Memory
      {{- if .Values.persistence.enabled }}
      - name: shared-volume
        persistentVolumeClaim:
          claimName: {{ .Values.persistence.name }}
      {{- end }}
      {{- if .Values.invenio.vocabularies }}
      - name: vocabularies
        configMap:
          name: "{{ include "invenio.fullname" . }}-vocabularies"
      {{- end }}
      {{- if .Values.worker.imagePullSecret }}
      imagePullSecrets:
      - name: {{ .Values.worker.imagePullSecret }}
      {{- end }}
  strategy:
    type: Recreate # For data safety, beat must never have more than 1 replica!
