---
apiVersion: v1
kind: ConfigMap
metadata:
  name: haproxy-config
data:
  haproxy.cfg: |
    global
      quiet

    defaults
      mode http
      maxconn 3000

      stats enable
      stats uri /stats
      stats hide-version

      timeout  http-request 10s
      timeout  queue 2m
      timeout  connect 10s
      timeout  client 2m
      timeout  server 2m
      timeout  http-keep-alive 10s
      timeout  check 10s

    frontend public
      bind *:8080
      acl is_static path_beg -i /static /robots.txt
      default_backend apps
      use_backend     static if is_static

    backend apps
      http-check disable-on-404
      option httpchk OPTIONS /ping HTTP/1.1\nHost:\ {{ .Values.host }}
      option http-server-close

      server web web:80 check fall 2 inter 5000 maxconn {{ .Values.haproxy.maxconn }}

    backend static
      server web web:80 check fall 2 inter 5000 maxconn {{ .Values.haproxy.maxconn_static }}
