---
apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-config
data:
  invenio.conf: |
    upstream web {
        server 127.0.0.1:5000 max_conns={{ .Values.nginx.max_conns }};
    }
    log_format trace '$remote_addr - $time_iso8601 "$request" '
        '$status  $body_bytes_sent $request_length "$http_referer"  '
        '"$http_user_agent" "$http_x_forwarded_for" rid=$request_id '
        'rt=$request_time uct="$upstream_connect_time" '
        'uht="$upstream_header_time" urt="$upstream_response_time" '
        'sid=$upstream_http_x_session_id uid=$upstream_http_x_user_id';

    access_log  /var/log/nginx/access.log  trace;

    server {
        listen 8080;
        server_name localhost;
        charset utf-8;

        location /ping {
            access_log off;
            return 200 "ok\n";
        }

        location / {
            include uwsgi_params;
            uwsgi_pass web;
            uwsgi_param X-Real-IP $remote_addr;
            # Sets buffering off since it creates download problems
            # when clients are slow to consume the buffer which uwsgi
            # creates by default (1GB). As a result uwsgi times out
            # by the time the client consumed the buffer.
            uwsgi_buffering off;
            uwsgi_request_buffering off;
            uwsgi_param Host $host;
            uwsgi_param X-Forwarded-For $proxy_add_x_forwarded_for;
            uwsgi_param X-Forwarded-Proto $http_x_forwarded_proto;
            uwsgi_ignore_headers Set-Cookie;
            {{- if .Values.ingress.class }}
            client_max_body_size {{ .Values.nginx.client_max_body_size }};
            {{- end }}
        }
        location /static {
          alias "{{ .Values.nginx.assets.location }}";
          autoindex off;
        }
    }
