{{- if not (.Values.rabbitmq.existing_secret) }}
---
apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: {{ .Values.rabbitmq.secret_name }}
  labels:
    app: {{ .Values.rabbitmq.secret_name }}
  annotations:
    helm.sh/resource-policy: keep
data:
  RABBITMQ_DEFAULT_PASS: {{ .Values.rabbitmq.default_password | b64enc }}
  CELERY_BROKER_URL: {{ .Values.rabbitmq.celery_broker_uri | b64enc }}

{{- end -}}
{{- if not (.Values.flower.existing_secret) }}
---
{{- $credentials := printf "flower:%s" .Values.flower.default_password }}
apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: {{ .Values.flower.secret_name }}
  labels:
    app: {{ .Values.flower.secret_name }}
  annotations:
    helm.sh/resource-policy: keep
data:
  FLOWER_BASIC_AUTH_CREDENTIALS: {{ $credentials | b64enc}}

{{- end -}}
{{- if not (.Values.postgresql.existing_secret) }}
---
apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: {{ .Values.postgresql.secret_name }}
  labels:
    app: {{ .Values.postgresql.secret_name }}
  annotations:
    helm.sh/resource-policy: keep
data:
  POSTGRESQL_USER: {{ .Values.postgresql.user | b64enc }}
  POSTGRESQL_PASSWORD: {{ .Values.postgresql.password | b64enc }}
  POSTGRESQL_HOST: {{ .Values.postgresql.host | b64enc }}
  POSTGRESQL_PORT: {{ .Values.postgresql.port | b64enc }}
  POSTGRESQL_DATABASE: {{ .Values.postgresql.database | b64enc }}
  SQLALCHEMY_DB_URI: {{ .Values.postgresql.sqlalchemy_db_uri | b64enc }}

{{- end -}}
{{- if not (.Values.search.existing_secret) }}
---
apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: {{ .Values.search.secret_name }}
  labels:
    app: {{ .Values.search.secret_name }}
  annotations:
    helm.sh/resource-policy: keep
data:
  SEARCH_USER: {{ .Values.search.user | b64enc }}
  SEARCH_PASSWORD: {{ .Values.search.password | b64enc }}
  INVENIO_SEARCH_HOSTS: {{ .Values.search.invenio_hosts | b64enc }}

{{- end -}}
{{- if and (.Values.invenio.sentry.enabled) (not .Values.invenio.sentry.existing_secret) }}
---
apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: {{ .Values.invenio.sentry.secret_name }}
  labels:
    app: {{ .Values.invenio.sentry.secret_name }}
  annotations:
    helm.sh/resource-policy: keep
data:
  SENTRY_DSN: {{ .Values.invenio.sentry.dsn | b64enc }}

{{- end -}}
{{- if and (.Values.invenio.remote_apps.enabled) (not .Values.invenio.remote_apps.existing_secret) }}
---
apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: {{ .Values.invenio.remote_apps.secret_name }}
  labels:
    app: {{ .Values.invenio.remote_apps.secret_name }}
  annotations:
    helm.sh/resource-policy: keep
data:
  {{- range .Values.invenio.remote_apps.credentials }}
  {{ default (printf "INVENIO_%s_APP_CREDENTIALS" .name) }}: {{ printf "{\"consumer_key\": \"%s\" , \"consumer_secret\": \"%s\"}" .consumer_key .consumer_secret | b64enc }}
  {{- end }}

{{- end -}}
{{- if not (.Values.invenio.existing_secret) }}
---
apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: invenio-secrets
  labels:
    app: invenio-secrets
  annotations:
    helm.sh/resource-policy: keep
data:
  INVENIO_SECRET_KEY: {{ .Values.invenio.secret_key | b64enc }}
  INVENIO_SECURITY_LOGIN_SALT: {{ .Values.invenio.security_login_salt | b64enc }}
  INVENIO_CSRF_SECRET_SALT: {{ .Values.invenio.csrf_secret_salt | b64enc }}

{{- end -}}
{{- if and (.Values.invenio.datacite.enabled) (not .Values.invenio.datacite.existing_secret)}}
---
apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: datacite-secrets
  labels:
    app: datacite-secrets
  annotations:
    helm.sh/resource-policy: keep
data:
  DATACITE_PASSWORD: {{ .Values.invenio.datacite.password | b64enc }}
  DATACITE_USERNAME: {{ .Values.invenio.datacite.username | b64enc }}
{{- end -}}

{{- if .Values.invenio.extra_secrets }}
{{- range $key, $value := .Values.invenio.extra_secrets }}
{{- if and ($value.enabled) (not $value.existing_secret)}}
---
apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: {{ $value.secret_name }}
  labels:
    app: {{ $value.secret_name }}
  annotations:
    helm.sh/resource-policy: keep
data:
    {{- range $secret_key, $secret_value := $value }}
    {{ $secret_key }}: {{ $secret_value | toYaml | indent 4 | trim }}
    {{- end }}
{{- end }}
{{- end }}

{{- end -}}
