---
{{- if not (.Values.rabbitmq.invenio.existing_secret) }}
apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: {{ .Values.rabbitmq.invenio.secret_name }}
  labels:
    app: {{ .Values.rabbitmq.invenio.secret_name }}
  annotations:
    helm.sh/resource-policy: keep
data:
  RABBITMQ_DEFAULT_PASS: {{ .Values.rabbitmq.auth.password  | b64enc }}
{{- $host := include "rabbitmq.host_name" . }}
  CELERY_BROKER_URL: {{ (printf "amqp://%s:%s@%s:%s" .Values.rabbitmq.auth.username .Values.rabbitmq.auth.password $host (.Values.rabbitmq.service.ports.amqp | toString)) | b64enc }}

---
{{- end -}}
{{- if not (.Values.postgresql.invenio.existing_secret) }}
apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: {{ .Values.postgresql.global.postgresql.auth.existingSecret }}
  labels:
    app: {{ .Values.postgresql.global.postgresql.auth.existingSecret }}
    app.kubernetes.io/managed-by: Helm
  annotations:
    helm.sh/resource-policy: keep
    meta.helm.sh/release-name: {{ .Release.Name }}
    meta.helm.sh/release-namespace: {{ .Release.Namespace }}
stringData:
  POSTGRESQL_USER: {{ .Values.postgresql.global.postgresql.auth.username }}
  POSTGRESQL_PASSWORD: {{ .Values.postgresql.invenio.password }}
  POSTGRESQL_PORT: {{ .Values.postgresql.invenio.port }}
  POSTGRESQL_DATABASE: {{ .Values.postgresql.invenio.database }}
{{- if .Values.postgresql.invenio.enabled }}
{{- $host := include "postgresql.primary.fullname" .Subcharts.postgresql }}
  POSTGRESQL_HOST: {{ $host }}
  SQLALCHEMY_DB_URI: {{ printf "postgresql+psycopg2://%s:%s@%s:%s/%s" .Values.postgresql.global.postgresql.auth.username .Values.postgresql.invenio.password $host .Values.postgresql.invenio.port .Values.postgresql.invenio.database }}
{{- else }}
{{- $host := .Values.postgresql.invenio.host }}
  POSTGRESQL_HOST: {{ $host }}
  SQLALCHEMY_DB_URI: {{ printf "postgresql+psycopg2://%s:%s@%s:%s/%s" .Values.postgresql.global.postgresql.auth.username .Values.postgresql.invenio.password $host .Values.postgresql.invenio.port .Values.postgresql.invenio.database }}
{{- end }}
---
{{- end -}}
{{- if not (.Values.search.invenio.existing_secret) }}
apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: {{ .Values.search.invenio.secret_name }}
  labels:
    app: {{ .Values.search.invenio.secret_name }}
    app.kubernetes.io/managed-by: Helm
  annotations:
    helm.sh/resource-policy: keep
    meta.helm.sh/release-name: {{ .Release.Name }}
    meta.helm.sh/release-namespace: {{ .Release.Namespace }}
stringData:
  SEARCH_USER: {{ .Values.search.invenio.user }}
  SEARCH_PASSWORD: {{ .Values.search.invenio.password }}
{{- if .Values.search.invenio.enabled }}
{{- $host := include "opensearch.serviceName" .Subcharts.search }}
  INVENIO_SEARCH_HOSTS: {{ printf "[{'host': '%s'}]" $host }}
{{- else }}
{{- $host := .Values.search.invenio.host }}
  INVENIO_SEARCH_HOSTS: {{ printf "[{'host': '%s'}]" $host }}
{{- end }}

---
{{- end -}}
{{- if and (.Values.invenio.sentry.enabled) (not .Values.invenio.sentry.existing_secret) }}
apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: {{ .Values.invenio.sentry.secret_name }}
  labels:
    app: {{ .Values.invenio.sentry.secret_name }}
  annotations:
    helm.sh/resource-policy: keep
data:
  SENTRY_DSN: {{ .Values.invenio.sentry.dsn | b64enc }}

---
{{- end -}}
{{- if and (.Values.invenio.remote_apps.enabled) (not .Values.invenio.remote_apps.existing_secret) }}
apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: {{ .Values.invenio.remote_apps.secret_name }}
  labels:
    app: {{ .Values.invenio.remote_apps.secret_name }}
  annotations:
    helm.sh/resource-policy: keep
data:
  {{- range .Values.invenio.remote_apps.credentials }}
  {{ default (printf "INVENIO_%s_APP_CREDENTIALS" .name) }}: {{ printf "{\"consumer_key\": \"%s\" , \"consumer_secret\": \"%s\"}" .consumer_key .consumer_secret | b64enc }}
  {{- end }}

---
{{- end -}}
{{- if not (.Values.invenio.existing_secret) }}
apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: invenio-secrets
  labels:
    app: invenio-secrets
  annotations:
    helm.sh/resource-policy: keep
data:
  INVENIO_SECRET_KEY: {{ .Values.invenio.secret_key | b64enc }}
  INVENIO_SECURITY_LOGIN_SALT: {{ .Values.invenio.security_login_salt | b64enc }}
  INVENIO_CSRF_SECRET_SALT: {{ .Values.invenio.csrf_secret_salt | b64enc }}

---
{{- end -}}
{{- if and (.Values.invenio.datacite.enabled) (not .Values.invenio.datacite.existing_secret)}}
apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: datacite-secrets
  labels:
    app: datacite-secrets
  annotations:
    helm.sh/resource-policy: keep
data:
  DATACITE_PASSWORD: {{ .Values.invenio.datacite.password | b64enc }}
  DATACITE_USERNAME: {{ .Values.invenio.datacite.username | b64enc }}
{{- end -}}
